declare module '*.jpg';
declare module '*.jpeg';
declare module '*.png';
declare module '*.svg';
declare module '*.gif';
declare module '*.avif';
declare module '*.webp';
declare module '*.woff';
declare module '*.woff2';
